/*
 * This file is generated by jOOQ.
*/
package my.db.public_.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Plans implements Serializable {

    private static final long serialVersionUID = -1426286140;

    private Integer id;
    private String  name;
    private String  decription;
    private Date    dateAdded;
    private Integer userid;

    public Plans() {}

    public Plans(Plans value) {
        this.id = value.id;
        this.name = value.name;
        this.decription = value.decription;
        this.dateAdded = value.dateAdded;
        this.userid = value.userid;
    }

    public Plans(
        Integer id,
        String  name,
        String  decription,
        Date    dateAdded,
        Integer userid
    ) {
        this.id = id;
        this.name = name;
        this.decription = decription;
        this.dateAdded = dateAdded;
        this.userid = userid;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDecription() {
        return this.decription;
    }

    public void setDecription(String decription) {
        this.decription = decription;
    }

    public Date getDateAdded() {
        return this.dateAdded;
    }

    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }

    public Integer getUserid() {
        return this.userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Plans (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(decription);
        sb.append(", ").append(dateAdded);
        sb.append(", ").append(userid);

        sb.append(")");
        return sb.toString();
    }
}
