/*
 * This file is generated by jOOQ.
*/
package my.db.public_.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = -2087884233;

    private Integer id;
    private String  name;
    private String  lastname;
    private String  email;
    private String  password;

    public Users() {}

    public Users(Users value) {
        this.id = value.id;
        this.name = value.name;
        this.lastname = value.lastname;
        this.email = value.email;
        this.password = value.password;
    }

    public Users(
        Integer id,
        String  name,
        String  lastname,
        String  email,
        String  password
    ) {
        this.id = id;
        this.name = name;
        this.lastname = lastname;
        this.email = email;
        this.password = password;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(lastname);
        sb.append(", ").append(email);
        sb.append(", ").append(password);

        sb.append(")");
        return sb.toString();
    }
}
