/**
 * This class is generated by jOOQ
 */
package com.crownzeh.db;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>public.plans_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Integer> PLANS_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Integer>("plans_id_seq", com.crownzeh.db.Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

	/**
	 * The sequence <code>public.users_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Integer> USERS_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Integer>("users_id_seq", com.crownzeh.db.Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
