/**
 * This class is generated by jOOQ
 */
package com.crownzeh.db;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.plans
	 */
	public static final com.crownzeh.db.tables.Plans PLANS = com.crownzeh.db.tables.Plans.PLANS;

	/**
	 * The table public.users
	 */
	public static final com.crownzeh.db.tables.Users USERS = com.crownzeh.db.tables.Users.USERS;
}
