/**
 * This class is generated by jOOQ
 */
package com.crownzeh.db.tables.records;

import java.sql.Date;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlansRecord extends org.jooq.impl.UpdatableRecordImpl<com.crownzeh.db.tables.records.PlansRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.String, java.lang.String, java.sql.Date, java.lang.Integer> {

	private static final long serialVersionUID = 1235820267;

	/**
	 * Setter for <code>public.plans.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.plans.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.plans.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.plans.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.plans.decription</code>.
	 */
	public void setDecription(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.plans.decription</code>.
	 */
	public java.lang.String getDecription() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.plans.date_added</code>.
	 */
	public void setDateAdded(java.sql.Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.plans.date_added</code>.
	 */
	public java.sql.Date getDateAdded() {
		return (java.sql.Date) getValue(3);
	}

	/**
	 * Setter for <code>public.plans.userid</code>.
	 */
	public void setUserid(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.plans.userid</code>.
	 */
	public java.lang.Integer getUserid() {
		return (java.lang.Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.sql.Date, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.sql.Date, java.lang.Integer> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.crownzeh.db.tables.Plans.PLANS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.crownzeh.db.tables.Plans.PLANS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.crownzeh.db.tables.Plans.PLANS.DECRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field4() {
		return com.crownzeh.db.tables.Plans.PLANS.DATE_ADDED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return com.crownzeh.db.tables.Plans.PLANS.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDecription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value4() {
		return getDateAdded();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlansRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlansRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlansRecord value3(java.lang.String value) {
		setDecription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlansRecord value4(java.sql.Date value) {
		setDateAdded(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlansRecord value5(java.lang.Integer value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlansRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.sql.Date value4, java.lang.Integer value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PlansRecord
	 */
	public PlansRecord() {
		super(com.crownzeh.db.tables.Plans.PLANS);
	}

	/**
	 * Create a detached, initialised PlansRecord
	 */
	public PlansRecord(java.lang.Integer id, java.lang.String name, java.lang.String decription, java.sql.Date dateAdded, java.lang.Integer userid) {
		super(com.crownzeh.db.tables.Plans.PLANS);

		setValue(0, id);
		setValue(1, name);
		setValue(2, decription);
		setValue(3, dateAdded);
		setValue(4, userid);
	}

	@Override
	public Integer component1() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String component2() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String component3() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Date component4() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Integer component5() {
		// TODO Auto-generated method stub
		return null;
	}
}
