/*
 * This file is generated by jOOQ.
*/
package my.db.public_.tables.daos;


import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import my.db.public_.tables.Plans;
import my.db.public_.tables.records.PlansRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlansDao extends DAOImpl<PlansRecord, my.db.public_.tables.pojos.Plans, Integer> {

    /**
     * Create a new PlansDao without any configuration
     */
    public PlansDao() {
        super(Plans.PLANS, my.db.public_.tables.pojos.Plans.class);
    }

    /**
     * Create a new PlansDao with an attached configuration
     */
    public PlansDao(Configuration configuration) {
        super(Plans.PLANS, my.db.public_.tables.pojos.Plans.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(my.db.public_.tables.pojos.Plans object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<my.db.public_.tables.pojos.Plans> fetchById(Integer... values) {
        return fetch(Plans.PLANS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public my.db.public_.tables.pojos.Plans fetchOneById(Integer value) {
        return fetchOne(Plans.PLANS.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<my.db.public_.tables.pojos.Plans> fetchByName(String... values) {
        return fetch(Plans.PLANS.NAME, values);
    }

    /**
     * Fetch records that have <code>decription IN (values)</code>
     */
    public List<my.db.public_.tables.pojos.Plans> fetchByDecription(String... values) {
        return fetch(Plans.PLANS.DECRIPTION, values);
    }

    /**
     * Fetch records that have <code>date_added IN (values)</code>
     */
    public List<my.db.public_.tables.pojos.Plans> fetchByDateAdded(Date... values) {
        return fetch(Plans.PLANS.DATE_ADDED, values);
    }

    /**
     * Fetch records that have <code>userid IN (values)</code>
     */
    public List<my.db.public_.tables.pojos.Plans> fetchByUserid(Integer... values) {
        return fetch(Plans.PLANS.USERID, values);
    }
}
