/*
 * This file is generated by jOOQ.
*/
package my.db.public_;


import javax.annotation.Generated;

import my.db.public_.tables.Plans;
import my.db.public_.tables.Users;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.plans</code>.
     */
    public static final Plans PLANS = my.db.public_.tables.Plans.PLANS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = my.db.public_.tables.Users.USERS;
}
