/**
 * This class is generated by jOOQ
 */
package com.crownzeh.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.3" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Plans extends org.jooq.impl.TableImpl<com.crownzeh.db.tables.records.PlansRecord> {

	private static final long serialVersionUID = -1461995537;

	/**
	 * The singleton instance of <code>public.plans</code>
	 */
	public static final com.crownzeh.db.tables.Plans PLANS = new com.crownzeh.db.tables.Plans();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.crownzeh.db.tables.records.PlansRecord> getRecordType() {
		return com.crownzeh.db.tables.records.PlansRecord.class;
	}

	/**
	 * The column <code>public.plans.id</code>.
	 */
	public final org.jooq.TableField<com.crownzeh.db.tables.records.PlansRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.plans.name</code>.
	 */
	public final org.jooq.TableField<com.crownzeh.db.tables.records.PlansRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>public.plans.decription</code>.
	 */
	public final org.jooq.TableField<com.crownzeh.db.tables.records.PlansRecord, java.lang.String> DECRIPTION = createField("decription", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>public.plans.date_added</code>.
	 */
	public final org.jooq.TableField<com.crownzeh.db.tables.records.PlansRecord, java.sql.Date> DATE_ADDED = createField("date_added", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * The column <code>public.plans.userid</code>.
	 */
	public final org.jooq.TableField<com.crownzeh.db.tables.records.PlansRecord, java.lang.Integer> USERID = createField("userid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.plans</code> table reference
	 */
	public Plans() {
		this("plans", null);
	}

	/**
	 * Create an aliased <code>public.plans</code> table reference
	 */
	public Plans(java.lang.String alias) {
		this(alias, com.crownzeh.db.tables.Plans.PLANS);
	}

	private Plans(java.lang.String alias, org.jooq.Table<com.crownzeh.db.tables.records.PlansRecord> aliased) {
		this(alias, aliased, null);
	}

	private Plans(java.lang.String alias, org.jooq.Table<com.crownzeh.db.tables.records.PlansRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.crownzeh.db.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.crownzeh.db.tables.records.PlansRecord, java.lang.Integer> getIdentity() {
		return com.crownzeh.db.Keys.IDENTITY_PLANS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.crownzeh.db.tables.records.PlansRecord> getPrimaryKey() {
		return com.crownzeh.db.Keys.PLANS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.crownzeh.db.tables.records.PlansRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.crownzeh.db.tables.records.PlansRecord>>asList(com.crownzeh.db.Keys.PLANS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.crownzeh.db.tables.records.PlansRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.crownzeh.db.tables.records.PlansRecord, ?>>asList(com.crownzeh.db.Keys.PLANS__PLANS_USERID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.crownzeh.db.tables.Plans as(java.lang.String alias) {
		return new com.crownzeh.db.tables.Plans(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.crownzeh.db.tables.Plans rename(java.lang.String name) {
		return new com.crownzeh.db.tables.Plans(name, null);
	}
}
